baseURL = "https://princeton-cdh.github.io/athens2023/"
languageCode = "en-US"
title = "Summer Institute: Digital Humanities for Hellenic Studies"
theme = "athens2023"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
enableEmoji = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = true
      footnote = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = 'dracula'
      # options: https://xyproto.github.io/splash/docs/all.html
      tabWidth = 4
    [markup.tableOfContents]
      endLevel = 4
      ordered = false
      startLevel = 2
